### ISSUE TITLE
Security Issue - Forcing the whole process to use TLS1

### ISSUE THREAD

**Issue by cosminonea** [Azure/azure-documentdb-node#100]
https://github.com/Azure/azure-documentdb-node/blob/1ef1570fb2390b8f324eb8d194db801cece93f46/source/lib/request.js#L35

Is there any reason for that line?
I am using the document db client in an app together with the paypal client and paypal rejects tls 1 connections as it only accepts tls 1.2

**Comment by pierre-elie** [comment]
Totally agree, modifying the global agent is to absolutely avoid in a lib, IMHO.
Adressed in PR #101.

**Comment by ryancrawcour** [comment]
Just testing locally before accepting and closing.
