### ISSUE TITLE
Continuation token is not passed properly on query

### ISSUE THREAD

**Issue by htuomola** [Azure/azure-documentdb-node#107]
I think DocumentDbClient does not properly send the continuation token on request even if has been set to `queryOptions.continuation` property. I'm having a problem querying "next page" of items by passing a continuation token to `documentDbClient.queryDocuments` in query options. I always get the same result set back, with iterator.continuation always reporting the same token after the call. I've tested this with latest NPM package, v.1.5.5.

I've created a full repro at https://gist.github.com/htuomola/620f13f572a2dfd4618a (apart from credentials and DB info). I also tried to debug it but my javascript-fu is not strong enough to understand what's wrong. FWIW, based on debugging the error seems to be in `queryIterator._fetchMore()`, where the continuation token gets somehow lost. I modified it so it logs `this.options.continuation` both before and after setting it (queryiterator.js, line 219), like this:

``` javascript
_fetchMore: function(callback){
   var that = this;
   console.log('continuation 1: '+this.options.continuation)
   this.options.continuation = this.continuation;
   console.log('continuation 2: '+this.options.continuation)
   [..]
```

The result is:

```
continuation 1: +RID:<redacted>#RT:1#TRC:1#RTD:<redacted>
continuation 2: null
```

ps. Contribution guidelines link in contributing.md is broken.

**Comment by ryancrawcour** [comment]
we have found a bug in the node driver where the iterator is not respecting the options.continuation. 
a workaround for this is to set the continuation on your iterator explicitly. 

you don't actually need to pass the continuation token around, the iterator keeps this internally. so an alternate to your code might be something like this [gst](https://gist.github.com/ryancrawcour/f01a502bb4e970c9af4d) where we recursively walk the results 10 records at a time. 

if you want to control this and not walk the full result set, then just set the continuation on the iterator itself.

so after line [#43](https://gist.github.com/htuomola/620f13f572a2dfd4618a) add the following line
iterator.continuation = opts.continuation;

**Comment by htuomola** [comment]
Right, that seems to fix it for now. Thanks for the prompt reply. I know the same iterator can be used to get multiple pages but I'm working in a disconnected (web API) scenario where the "next page" is a separate request.

**Comment by ryancrawcour** [comment]
yeah, we've added a work item to have the iterator respect the options passed to it.

**Comment by stefan-akelius** [comment]
This seems to be still valid. I am in the same position to write a api that just delivers one page of results and - if there are more - the additional continuation token. But no matter what, the results are always the same and the continuation token does not get updated. Is there any eta on this?

**Comment by stefan-akelius** [comment]
It seems the bug is in [defaultQueryExecutionContext.js](https://github.com/Azure/azure-documentdb-node/blob/master/source/lib/queryExecutionContext/defaultQueryExecutionContext.js). On line `47` in the constructor `this.continuation` is set to `null` instead of `options.continuation`. And in line `119` this happens `this.options.continuation = this.continuation;`. So the passed continuation token is never taken into account and the DocumentDB always sends back the same page.

**Comment by rnagpal** [comment]
@stefan-akelius I believe assigning continuation to null happens only in the constructor which is expected. There are APIs that are supposed to take care of passing continuation for a paged query as you ask for next page. That seems to happen in fetchMore method here. As an API user, you just need to call executeNext on the queryIterator and it takes care of passing the continuation internally. This is how getting paged results is supposed to work. We found a related bug in defaultQueryExecutionContext.js that we need to fix, so if you can please try the executeNext approach and let us know if that works for you.

@moderakh : Should also be able to help you with this.

**Comment by stefan-akelius** [comment]
@rnagpal 
There is still the bug in there that `this.continuation` is never overwritten with the returned token which is what I changed.

Your supposed way does not work for an API scenario. Imagine you have 15000 documents but want to transfer only 25 per request (paginated for a frontend). How is the client supposed to tell the server to get the next page? Waiting for the sdk to retrieve all 15000 docs will take way too much time.

The azure-storage sdk for the Table Storage handles this very well. You get a result object back that looks like this:

```javascript
{
  entries: Array<TableEntity>,
  continuationToken: Object
}
``` 

You can then send the continuation token object to the client alongside the data, he sends it back with the next request and you simply pass it to the sdk and get the next page.

**Comment by rnagpal** [comment]
@moderakh will be looking at this and merging the PR.

**Comment by rnagpal** [comment]
This has been fixed in the latest Node.js SDK.
