### ISSUE TITLE
cannot access collection named "media"

### ISSUE THREAD

**Issue by claudio-destro-banzai** [Azure/azure-documentdb-node#114]
Hi guys!

it seems a collection with "media" in its name is **not** accessible!

documentdb/lib/request.js line 53 is suspicious :)

var isMedia = ( requestOptions.path.indexOf("media") > -1 );

Bonus question: how do I name my media collections?

**Comment by claudio-destro-banzai** [comment]
for the sake of my (and maybe someone else) sanity, just use letter case ... e.g.: "Media"

**Comment by moderakh** [comment]
fixed in 1.12.2
