### ISSUE TITLE
Proxy Support

### ISSUE THREAD

**Issue by dillten** [Azure/azure-documentdb-node#116]
Can we have proxy server support added to the node library? This is blocking use in an environment I have. 

Ref on a similar request in the java SDK: https://github.com/Azure/azure-documentdb-java/pull/22

**Comment by ryancrawcour** [comment]
Would be happy to add this to the backlog. If you want this sooner, we'd be happy to accept Pull Requests.

**Comment by ButchersBoy** [comment]
Any eta?  This is a blocker certainly for me and I would imagine many other people working in enterprise.

**Comment by rnagpal** [comment]
@ButchersBoy We haven't got to this yet but if you could send us a PR with the changes, we can get it reviewed and merged sooner.

**Comment by christopheranderson** [comment]
This is supported.

**Comment by gratereaux** [comment]
This issue is close... so what`s the solution?
