### ISSUE TITLE
Which version of node is required?

### ISSUE THREAD

**Issue by bingosummer** [Azure/azure-documentdb-node#129]
Can all node versions (`0.x`, `4.x`, `5.x`) work with `azure-documentdb-node`? Thanks in advance.

**Comment by rnagpal** [comment]
We have tested with 0.x and 4.x but not 5.x. Let us know if you run into any issue with any of the versions you have installed.

**Comment by digitalclover** [comment]
I haven't had any issues running this on 5.x or 6.x.  However, I would recommend running on at least 5.4 to avoid issue #102

**Comment by bingosummer** [comment]
Thanks @rnagpal and @digitalclover .
We actually hit an issue on `4.x` and `0.x`, but we did not note the exact error message. We are trying to reproduce the error.

CC: @sebastus

**Comment by rnagpal** [comment]
@bingosummer : Feel free to open an issue with the repro steps if you run into any problem. azure-documentdb-node itself doesn't enforces any specific version and gets the latest version from npm.
