### ISSUE TITLE
"Cannot read property 'partitionKey' of null" on createDocument

### ISSUE THREAD

**Issue by SteenMolberg** [Azure/azure-documentdb-node#134]
I get this error
"Cannot read property 'partitionKey' of null"
 when trying to create a new document with...
this.client.createDocument(this.link, item, null, this.resultHandler(callback));

I had to pass an empty object for options like this...
this.client.createDocument(this.link, item, {}, this.resultHandler(callback));
to make it work.

**Comment by digitalclover** [comment]
Since the 'options' parameter is optional, you shouldn't have to place 'null' or an empty object.  If you don't want any options, just skip straight to the callback function.

```this.client.createDocument(this.link, item, this.resultHandler(callback));```

Let me know if that works for you.

**Comment by moderakh** [comment]
thanks @SteenMolberg for the question and @digitalclover  for your answer.

I am closing this as it is not an issue with the SDK.
