### ISSUE TITLE
How to tag the documentdb database?

### ISSUE THREAD

**Issue by bingosummer** [Azure/azure-documentdb-node#136]
I would like to add tag for the documentdb database. Is it doable?
Thanks in advance.

**Comment by stephbaron** [comment]
Do you mean add an Azure tag (key/value pairs enabling you to categorize resources)?  If so, only DocumentDB accounts can be tagged today.  Databases and collections are not "taggable" at present.

**Comment by bingosummer** [comment]
Thanks @stephbaron for the clarification.
