### ISSUE TITLE
Make samples simplier by removing Self-Links 

### ISSUE THREAD

**Issue by yvele** [Azure/azure-documentdb-node#138]
For someone like me that is learning documentDB, I think that the samples should be updated as they does not reflects [farewell to Self-Links](https://azure.microsoft.com/en-us/blog/azure-documentdb-bids-fond-farewell-to-self-links/).

Self-Links are confusing and adds so much overhead (specially for someone learning documentDB.. I lost precious time figuring how to deal with Self-Links.. and finally not using them)

**Comment by moderakh** [comment]
Hi @yvele I am sorry to hear that.

Could you please point to that part of sample which was confusing?

**Comment by christopheranderson** [comment]
This is a goal in v2. Closing since this is tracked there.
