### ISSUE TITLE
NPM package : Include only runtime useful files

### ISSUE THREAD

**Issue by yvele** [Azure/azure-documentdb-node#141]
Right now when running `npm install documentdb`, lots of useless files are installed and that adds considerable size to the package :

```none
8.0K	DocumentDB.Node.master.njsproj ----> USELESS
4.0K	DocumentDB.Node.master.sln ----> USELESS
4.0K	Gruntfile.js ----> USELESS
4.0K	changelog.md
4.0K	index.js
276K	lib
4.0K	package.json
4.0K	readme.html
340K	test ----> USELESS
4.0K	.editorconfig ----> USELESS
4.0K	.eslintrc ----> USELESS
4.0K	.npmignore
```

you should add the [files](https://docs.npmjs.com/files/package.json#files) field to the package.json :
```json
{
  "files" : ["lib"]
}
```

**Comment by rnagpal** [comment]
@yvele Thanks Yves for your feedback and we will look into this issue.

@moderakh: Can we fix this in our next update? We can still keep them in our GitHub but remove from our package.

**Comment by rnagpal** [comment]
@yvele : We have removed these files from our latest Node.js SDK release 1.10.0
