### ISSUE TITLE
Casing of enums TriggerType and TriggerOperation 

### ISSUE THREAD

**Issue by factormystic** [Azure/azure-documentdb-node#148]
`TriggerType` and `TriggerOperation` are all lower case in this sdk (https://github.com/Azure/azure-documentdb-node/blob/master/source/lib/documents.js#L234)

However, if you actually compile a trigger referencing these enums, the Script Explorer in the Azure Portal doesn't show the compiled option:

``` js
var DocumentBase = require('documentdb').DocumentBase;

module.exports = {
    id: "upperCaseName",
    body: function () {
        var req = getContext().getRequest();
        var item = req.getBody();
        item.name = item.name.toUpperCase();
        req.setBody(item);
    },
    triggerType: DocumentBase.TriggerType.Pre,
    triggerOperation: DocumentBase.TriggerOperation.All,
};
```

![image](https://cloud.githubusercontent.com/assets/43428/19629360/a2801e9c-9941-11e6-94ce-d4254e82b7f7.png)

If you manually type them in with title case, it works:

``` js
    triggerType: "Pre",
    triggerOperation: "All",
```

![image](https://cloud.githubusercontent.com/assets/43428/19629376/0ee503b8-9942-11e6-9d9a-6889d14a4075.png)

The trigger still works, though. I can't tell if this is an SDK glitch or a portal glitch. Which app defines the canonical casing? Should this SDK be corrected?

**Comment by ato9000** [comment]
Thanks for reporting this. It looks like a portal issue. We will keep this issue open and close once the portal is fixed.

**Comment by moderakh** [comment]
@ato9000 could you please comment on the status of this issue? Can I close this issue?

I would like to close this issue here as this is a portal issue not the sdk's.

**Comment by moderakh** [comment]
We created a issue in our internal issue tracking for portal. I am closing this issue here because this is an issue in portal not in nodejs sdk. @ato9000  please track the issue internally.
