### ISSUE TITLE
Meteor Support

### ISSUE THREAD

**Issue by jdnichollsc** [Azure/azure-documentdb-node#152]
Hi guys,

Exist any way to replace **MongoDB** with **DocumentDB** in **Meteor**?

Check this **Meteor** example please: https://github.com/meteor/todos

Thanks in advance, Nicholls

**Comment by moderakh** [comment]
@mingaliu could you please take a look at this?

**Comment by mingaliu** [comment]
Hi Nicholls,
    Can you ping me? We like to have a chat with you to understand your scenario better.

Thanks!
Ming

**Comment by meteorplus** [comment]
that would be awesome guys :D

I really need this :)

**Comment by moderakh** [comment]
This is an interesting suggestion. Please create a new entry in https://feedback.azure.com/forums/263030-documentdb and we will investigate from there.

**Comment by nadeemja** [comment]
There seems to have been an entry created @ feedback.azure.com for meteor support, but was it ever investigated?

**Comment by jdnichollsc** [comment]
Sorry @mingaliu, I changed company and I'm no longer working with Meteor :/

**Comment by meteorplus** [comment]
They won't support this  I no longer use Azure!

**Comment by juiyout** [comment]
For DocumentDB to work with Meteor, I believe Azure would need to have a more complete support for MongoDB API and provide OPLOG URL. At this moment, I don't think it is suitable.

As I understand, DocumentDB team sometimes need to balance between API compatibility and performance. I can completely understand as DocumentDB might have complete different internal workings than MongoDB.

Now, isn't Meteor DG working on GraphQL and somehow it has the potential to reduce the effort to hook up any DB in the future?

**Comment by meteorplus** [comment]
@juiyout it's pretty simple to throw a ready to use VM in their azure market but no they didn't want to do it!

also for graphql yes it will allow you to other DB but not simple since most meteor apps were meant to be used for mongodb but there is some good work for migration to new other DB (MySQL...) but just understand to migrate to another DB you will have to refractor a lot of code to make sure it works the right way!

**Comment by juiyout** [comment]
@meteorplus Ah, yes. They could just host MongoDB until their DocumentDB is compatible enough.

However, in this case, you could search for MongoDB in Azure market. There are MongoDB offer from Bitnami. I suppose you could just fire them up and see if it works. Never tried them myself though.

**Comment by christopheranderson** [comment]
Think it makes the most sense for folks trying to do this to use the Mongo API for Cosmos DB. 

Otherwise, this would be an issue for the Meteor application itself, but they are unlikely to want to use Cosmos DB due to being an Azure only product and they don't have direct support for running off their PaaS (to my knowledge, I could be wrong)...

**Comment by juiyout** [comment]
> Think it makes the most sense for folks trying to do this to use the Mongo API for Cosmos DB.
Still need OPLOG though, which CosmosDB has none.

**Comment by dgolds** [comment]
Is this sufficient for an OPLOG equivalent? https://docs.microsoft.com/en-us/azure/cosmos-db/change-feed.

>> The changes are persisted, can be processed asynchronously and incrementally, and the output can be distributed across one or more consumers for parallel processing.

**Comment by davidjytang** [comment]
> Is this sufficient for an OPLOG equivalent? https://docs.microsoft.com/en-us/azure/cosmos-db/change-feed.
> 
> > > The changes are persisted, can be processed asynchronously and incrementally, and the output can be distributed across one or more consumers for parallel processing.

Though it seems some custom tooling is needed, I reckon this is a good direction forward. I only wish this could be a drop-in replacement for OPLOG.

**Comment by meteorplus** [comment]
So Azure can't even Oplog? what a shame...
