### ISSUE TITLE
Async/await support

### ISSUE THREAD

**Issue by hfjallemark** [Azure/azure-documentdb-node#154]
Since async/await support in Node is on the horizon -- when will DocumentDB support it? Since async/await is just sugar on top of promises, I guess the real question is -- will DocumentDB support promises instead of callbacks?

**Comment by rnagpal** [comment]
DocumentDB has a promises based npm package as well. 

GitHub repo : https://github.com/Azure/azure-documentdb-node-q 
npm package : https://www.npmjs.com/package/documentdb-q-promises

Let me know if that works for you.

cc: @moderakh

**Comment by hfjallemark** [comment]
Ah, didn't know that. What's the reasoning behind going with Q instead of native promises, backwards compatibility? Do you know if Q is fully compatible and will work with async/await?

**Comment by jcormont** [comment]
As an alternative, I wrote a wrapper around the Node.js API specifically for use with TypeScript and/or ES6 (Babel, ES2015, whatever). Link: https://github.com/jcormont/documentdb-typescript

This does support async/await, as well as incorporating a more streamlined API that is somewhat inspired by the object oriented .NET API. Just take a look at the examples in the readme file. Perhaps this is closer to what you are looking for!

**Comment by hfjallemark** [comment]
Looks nice @jcormont!
