### ISSUE TITLE
executeStoredProcedure doesn't take 0 as single param

### ISSUE THREAD

**Issue by kapil-ms** [Azure/azure-documentdb-node#155]
The stored procedure gets `undefined` as input on passing `0` as the value of params to executeStoredProcedure. `[0]` works.

https://github.com/Azure/azure-documentdb-node/blob/master/source/lib/documentclient.js#L1921
this should instead be
`if(params !== null && params !== undefined  && params.constructor !== Array)`

**Comment by moderakh** [comment]
@kapil-ms what you are saying makes sense. Do you want to do a fix patch on github? I will merge your Pull Request.

**Comment by moderakh** [comment]
I am closing this issue as your pull request is merged.
