### ISSUE TITLE
Promises support

### ISSUE THREAD

**Issue by jdnichollsc** [Azure/azure-documentdb-node#170]
Hi guys,

In your examples you're using only callbacks, what do you think to support Javascript Promises too? (To avoid the callback hell) 
Check my example => http://slides.com/juandavidnicholls/promises#/3

Regards, Nicholls

**Comment by mingaliu** [comment]
We do have nodejs Q promise based SDK at https://github.com/Azure/azure-documentdb-node-q. The SDK is also published in npm.

**Comment by ronenteva** [comment]
Hey @mingaliu, it seems that the promise based SDK is not being updated as frequently as this one.

**Comment by jdnichollsc** [comment]
@mingaliu To improve the quality of the code and for maintenance purposes, I think it would be much better to have only one repository that support callbacks and promises.
Regards, Nicholls
