### ISSUE TITLE
Passing partition key when using azure DocumentDB and readDocument(link, options, callback)

### ISSUE THREAD

**Issue by schechd** [Azure/azure-documentdb-node#175]
Hi,
I have this function:
find: function (querySpec, callback) {

        var self = this;
        var options = {
                partitionKey: "myCustomKeyName"
        };
        self.client.queryDocuments(this.collectionUrl, querySpec,options).toArray(function (err, results) {
            if (err) {
                callback(err);

            } else {
                callback(null, results);
            }
        });
    }

However, no results are returned when calling queryDocuments with options and partitionKey.

What am I doing wrong?

Thank you,
David

**Comment by beneuto** [comment]
Did you find a resolution for this David?

I am having a similar issue.   Whilst I can't find it documented anywhere, setting the partitionKey option as you did has stopped the query returning an error to the effect that partition key needs to be set.   However, I get no results from a simple query.

**Comment by chhantyal** [comment]
@schechd did you find solution for this?
