### ISSUE TITLE
QueryIterator should use setImmediate for callbacks to avoid max call stack

### ISSUE THREAD

**Issue by ctstone** [Azure/azure-documentdb-node#176]
QueryIterator's _toArrayImplementation is a recursive/looping async implementation that calls its callback synchronously. This can lead to `RangeError: Maximum call stack size exceeded` for large result sets.

See more: http://stackoverflow.com/questions/20936486/node-js-maximum-call-stack-size-exceeded

The fix is to wrap the callback() in setImmediate or process.nextTick: http://stackoverflow.com/questions/15349733/setimmediate-vs-nexttick

**Comment by marcodalessandro** [comment]
+1

**Comment by mehdijazayeri3000** [comment]
I am trying to reproduce this problem but unfortunately I was not successful. May I know what your query is and how large is the result? Also, it'd be great if you could give us a code to reproduce it.

**Comment by moderakh** [comment]
@ctstone @marcodalessandro our team is looking into this. Could you please share your code for how to reproduce the call stack issue?
* what's your query?
* how many docs do you have?

**Comment by ctstone** [comment]
@mehdijazayeri3000, @moderakh, please see repro at https://github.com/ctstone/repro-documentdb-176

The key, I think, is the large maxItemCount, (5000) combined with large-ish documents. I added some logging to `defaultQueryExecutionContext.fetchMore` to see how many documents are coming down over the wire, and it fails when the number reaches around 4500 in one response. My average document size is around 2200 bytes.

In general, async methods should never be called recursively without using one of setImmediate, process.nextTick, or setTimeout. See the StackOverflow link in the OP for more details.

Thanks!

**Comment by moderakh** [comment]
@ctstone
Thank you for giving us more information. We will fix this.

**Comment by mehdijazayeri3000** [comment]
@ctstone Thank you so much. We will fix this as soon as possible.

**Comment by moderakh** [comment]
This has been fixed in our 1.12.2 release. Please try that out.
