### ISSUE TITLE
createDocument and upsertDocument set the `id` attribute of my original data

### ISSUE THREAD

**Issue by dwhieb** [Azure/azure-documentdb-node#184]
The `createDocument` and `upsertDocument` methods of the DocumentClient modify my original data object when invoked. Running code like the following code will add an `id` property to the `data` object.

```
const data = {
  firstName: `John`,
  lastName: `Smith`,
};

client.upsertDocument(collectionLink, data, (err, res) => {
  console.log(data.id); // returns a UUID, but should be undefined
  console.log(data.id === res.id); // logs true
});
```

The `body` parameter of the `upsertDocument` method gets passed to `upsertDocumentPrivate`, where an `id` is added to the data ([here](https://github.com/Azure/azure-documentdb-node/blob/master/source/lib/documentclient.js#L2088)). Same process with `createDocument`.

**Comment by christopheranderson** [comment]
Closing because this is an old issue and the problem isn't clear. Please open a new issue if this is still causing problems.
