### ISSUE TITLE
Export queryIterator class to allow promisification

### ISSUE THREAD

**Issue by harshithkashyap** [Azure/azure-documentdb-node#185]
`queryDocuments` and other methods return instance of queryIterator. I looked at the source code but it looks like QueryIterator is not exported and cannot be `require`d to promisify. We'll have to use bluebird promisify on each execution as below:
```
Promise.promisifyAll(db.queryDocuments(db.collectionUrl, querySpec))
.toArrayAsync()
```

**Comment by christopheranderson** [comment]
Addressed in the new major version (since it is already promisified). We will export the class, though, for testing/mocking purposes.
