### ISSUE TITLE
Support Incremental feed for readDocuments

### ISSUE THREAD

**Issue by DmitriyKirakosyan** [Azure/azure-documentdb-node#192]
Using documentDB REST API it is possible to make incremental fetch for documents.
It is achieved by using `A-IM` and `If-None-Match` headers, which is described here:
https://docs.microsoft.com/en-us/rest/api/documentdb/list-documents

It would be nice to have this feature in the Nodejs SDK.

**Comment by christopheranderson** [comment]
This is supported now.
