### ISSUE TITLE
Connecting to CosmosDB emulator gives 'Unauthorized' error

### ISSUE THREAD

**Issue by ghost** [Azure/azure-documentdb-node#194]
Hi,

I'm trying to call a executeStoredProcedure on CosmosDb emulator, but get the following error back:

"{"code":"Unauthorized","message":"The input authorization token can't serve the request. Please check that the expected payload is built as per the protocol, and check the key being used. Server used the following payload to sign: 'post\nsprocs\ndbs/(dbname)/colls/(collectionname)/sprocs/(sprocname)\nsun, 14 may 2017 11:33:26 gmt\n\n'\r\nActivityId: 3127c606-1a19-4f39-ad5d-38d744c8490f"}"

Above, the values in parenthesis are of my database, collection and stored procedure

I'm using the MasterKey provided for the emulator: C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==

Some debugging in the SDK code shows the Authorization header value in the request as: "type%3Dmaster%26ver%3D1.0%26sig%3DgqPgawlh%2BnVD%2BKyzyxMmkl7Tb0s75erI09cRJgjzgao%3D" and it changes with every request since it likely takes a hash of text containing timestamp.

Can you please guide through this?

I'm using CosmosDb emulator version 1.13.58.2.

**Comment by shaaraddalvi** [comment]
After going through some other issues in this repository, I found a comment that the id provided shouldn't contain a trailing '/'. Maybe we need to handle it in the code and remove it if one exists?

**Comment by mehdijazayeri3000** [comment]
Hi, I appreciate if you send a sample code so we can reproduce this problem.

**Comment by TE-yujianishiyama** [comment]
Hi, I have same problem...
I'm using emulator version: 1.13.58.2 / azure-documentdb-node : 1.12.0

   { Error: self signed certificate
       at Error (native)
       at TLSSocket.<anonymous> (_tls_wrap.js:1092:38)
       at emitNone (events.js:86:13)
       at TLSSocket.emit (events.js:185:7)
       at TLSSocket._finishInit (_tls_wrap.js:610:8)
       at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:440:38) code: 'DEPTH_ZERO_SELF_SIGNED_CERT' } }

**Comment by moderakh** [comment]
@TE-yujianishiyama this is related to SSL certificate validation and is different from the authorization issue reported.

Since emulator SSL certificate is self signed, the SDK fails to validate the emulator's self signed certificate. When working with emulator you should disable SSL verification at the node SDK side to avoid this.

There is an option for this: 
``connectionPolicy.DisableSSLVerification``
Please see this example:
https://github.com/Azure/azure-documentdb-node/blob/c4292a1170b785c2e5b525f87e19083285f6d0ed/source/test/sslVerificationTests.js#L52-L64

**Comment by TE-yujianishiyama** [comment]
@moderakh  Thanks 👍 　, ｍy test code was able to run in the local environment.

**Comment by moderakh** [comment]
@TE-yujianishiyama I am happy to hear that :-)

**Comment by jderus** [comment]
@moderakh 

Yeah, with your link I was able to get a workaround going. Thanks.
Something like:
```
var documentClient = require("documentdb").DocumentClient;
var lib = require("./node_modules/documentdb/lib/");
var documentBase = lib.DocumentBase;
```

But honestly, I think the recommendation in #187 is better for all.

**Comment by dilantha111** [comment]
@jderus  That didn't work for me. But I found this in the sample nodejs application they provide. And it worked for me. Just setting NODE_TLS_REJECT_UNAUTHORIZED to 0. we can set this in a npm start script. That's what exactly in the sample nodejs application which comes with cosmosDB local emulator.  `"scripts": {
    "start": "set NODE_TLS_REJECT_UNAUTHORIZED=0&& node app.js"
  },`
