### ISSUE TITLE
Document passing partitionKey to deleteDocument method when used with partitioned collection

### ISSUE THREAD

**Issue by harshithkashyap** [Azure/azure-documentdb-node#195]
From the docs [here](http://azure.github.io/azure-documentdb-node/DocumentClient.html), `deleteDocument` takes only `_self` link of the document as the mandatory parameter. But when the query is run against a partitioned collection, cosmosdb throws the following error:

```
{"errors":["The partition key supplied in x-ms-partitionkey header has fewer components than defined in the the collection."]}
```

As suggested by [this SO answer](http://stackoverflow.com/a/43002819/2254360), passing partition key via options object as below works.
```
deleteDocument(documentLink, {
    partitionKey: ['partitionKeyValueForTheDocument']
}, callback)
```

**Comment by tony-gutierrez** [comment]
This also makes it impossible to delete documents that were saved without a partition key. Also the PartitionKey(Undefined.value) seems to be missing from the node sdk.

**Comment by srinathnarayanan** [comment]
@harshithkashyap deleteDocument needs the partitionKey to be passed via the request Options. The docs have been updated to reflect the same. Thanks.

**Comment by tony-gutierrez** [comment]
That still doest address the fact that the Undefined.value constant is missing from the node SDK.

**Comment by srinathnarayanan** [comment]
@tony I have provided a work around on this thread : #222. Please check that out and let us know if you had any other questions!
