### ISSUE TITLE
Node v6.x support

### ISSUE THREAD

**Issue by krishnagopinath** [Azure/azure-documentdb-node#197]
[According to the release notes](https://docs.microsoft.com/en-us/azure/documentdb/documentdb-sdk-node), DocumentDB currently supports only up to v4.2.0. But [that version recently moved to maintenance](https://github.com/nodejs/LTS#lts-schedule1) and current LTS version is v6.x.

1) Would you guys support v6.x support in the future?
2) Is anyone in the community using this with Node v6.x and are there any known problems with it?

Thanks!

**Comment by moderakh** [comment]
@krishnagopinath thanks for your question. We will be looking into supporting v6.x

**Comment by meakyl** [comment]
It's working with v6.9.1 for a couple of month without compatibility issues on my project.
Doesn't mean it will work for everybody though.

**Comment by moderakh** [comment]
@krishnagopinath @meakyl thank you for your comments.
We officially support v6.x. That will be added to our officially supported platforms in the next few days.
And also the existing npm module just works fine with v6.x.

**Comment by moderakh** [comment]
node v6.x added to the officially supported versions:
https://docs.microsoft.com/en-us/azure/documentdb/documentdb-sdk-node
