### ISSUE TITLE
connection pool closing

### ISSUE THREAD

**Issue by lucarv** [Azure/azure-documentdb-node#199]
i am accessing my cosmos db with mongoose. i create a connection pool when i start my (very simple) app. i then get intermittent (but frequent) error messages from the API when searching the database (very simple query, {} on a collection with objects in it). the error is {"name":"MongoError","message":"pool destroyed"}. i search around and the suggestions i got were related to closing the connection pool with db.close(), but i am only closing the connection when exiting the app....
any hints?

**Comment by moderakh** [comment]
Hi @lucarv,

This seems to be a mongodb issue and I think you are not using our documentdb nodej sdk.
So please follow your question here:
https://feedback.azure.com/forums/599059-azure-cosmos-db-mongodb-api/suggestions/19361521-fix-bug-that-destroys-nodejs-mongodb-connection-po
