### ISSUE TITLE
Provide utility for query parameter escaping

### ISSUE THREAD

**Issue by jdconley** [Azure/azure-documentdb-node#20]
As it sits today this library requires you to do your own escaping when building SQL strings. A fluent dynamic SQL building api would be nice, but, a simple escape utility would be all I'd need when building queries based on user input. All the samples seem to ignore escaping parameters. I'm not really sure what all Bad Things users could do by manipulating queries as this is pretty new, but, I imagine there is something at least related to getting unauthorized access to data. :8ball:

**Comment by yvele** [comment]
You can now use SQL Parameterization in DocumentDB
https://azure.microsoft.com/fr-fr/blog/announcing-sql-parameterization-in-documentdb/

> DocumentDB supports queries with parameters expressed with the familiar @ notation. Parameterized SQL provides robust handling and escaping of user input, preventing accidental exposure of data through SQL injection.
