### ISSUE TITLE
Unauthorized, The input authorization token can't serve the request: url encoding issue

### ISSUE THREAD

**Issue by janl** [Azure/azure-documentdb-node#200]
Similar to #82, we’re seeing the error message in the title. The full error object is this:

```json
{
    "code":"Unauthorized",
    "message":"The input authorization token can\'t serve the request. Please check that the expected payload is built as per the protocol, and check the key being used. Server used the following payload to sign: \'put\\ndocs\\ndbs/testdb/colls/pouchdb-test-collection/docs/ÿattach-storeÿmd5-CRq749X7/wgSD6EQeGTuFg==\\nwed, 21 jun 2017 21:28:58 gmt\\n\\n\'\\r\\nActivityId: 9f9d22ea-9c51-4b4e-bd51-de7ca5a68c1e"
}
```

My doc id is `ÿattach-storeÿmd5-CRq749X7%2fwgSD6EQeGTuFg==` and as you can see it has a `%2f` in it, and the underlying auth system seems to do a URL-Decode on the input key when signing the request.

Is this expected behaviour? What is the recommended way to encode and decode keys in a way that it is safe with DocumentDB/CosmosDB?

Grateful for any help :)

**Comment by janl** [comment]
PS: this is on the emulator.

**Comment by moderakh** [comment]
@janl 
* If you try to use the DocumentDB/CosmosDB cloud endpoint does this work?
* Does your problem only apply to docs with special characters? if your doc has only alphabetical ASCII chars does this work?

**Comment by janl** [comment]
This question is specifically about how to encode slashes in keys.

**Comment by moderakh** [comment]
@mehdijazayeri3000 I think you already worked on a similar problem, can you please take a look at this?

**Comment by mehdijazayeri3000** [comment]
Authorization token eventually gets ENCODED however, it should not make a problem as it will be decoded on the server side.
Would you please provide us these information?
1. what operation are you trying to do? (create/read/update/remove on db/col/doc/user/...)
2. what are the resource names used? are you using any illegal character (['/', '\', '?', '#']) in resource names?
3. what kind of authorization is used? (masterkey/token/permissionFeed)

**Comment by moderakh** [comment]
We did a new release of 1.12.2
please test it and if this still is an issue feel free to reopen this bug.

**Comment by jbrozena22** [comment]
This needs to be re-opened, it's still a problem.

Using the latest version of the package (1.14.2)

Steps to reproduce:
0) create a database called databaseID and a collection called collectionID
1) create a new document in this collection using the portal online set it's ID to test%3A
2) Run the following code:

```
var DocumentClient = require('documentdb').DocumentClient;
var host = ''// ADD YOUR ENDPOINT
var masterKey = '' // ADD YOUR KEY
var client = new DocumentClient(host, {masterKey: masterKey});
var databaseId = 'databaseID'
var collectionId = 'collectionID'
var dbLink = 'dbs/' + databaseId;
var collLink = dbLink + '/colls/' + collectionId;
var id = 'test%3A'

var query = 'SELECT f.id FROM ' + collectionId + ' f WHERE f.id = \"' + id + '\"';

console.log(query)

var querySpec = {
   query: query
};

client.queryDocuments(collLink, querySpec).toArray(function (err, results) {
   if (err) {
       console.log(err)
   } else {
    if ( results && results.length > 0) {
      console.log('Able to query for the document by id')
      console.log(results[0])

      var docLink = collLink + '/docs/' + results[0]['id'];

      console.log(docLink)

      client.deleteDocument(docLink, (err, result) => {
        if (err) {
          console.log('but unable to delete it')
          console.log(err);
        } else {
          console.log('success', ind);
        }
      });
    }
   }
})
```

The result is the document is query-able via that ID, but when you go to delete it the OP's error shows up. I believe this is happening because %3A is the url encoding of a forward slash and somewhere along the way it's being decoded. If so, that means %3A should be added to the list of non-allowable characters to have in your ID.

**Comment by roghernandez** [comment]
2019 still getting this error as well

**Comment by southpolesteve** [comment]
@roghernandez @divyanshch89 which SDK version are you using? If this is on the latest v2 SDK, I'll reopen this issue over in that repo

**Comment by ribsthakkar** [comment]
@roghernandez I am experiencing this issue on Java SDK v2.4.3

**Comment by southpolesteve** [comment]
@ribsthakkar Can you open an issue on the Java repo? https://github.com/Azure/azure-cosmosdb-java This one is for our older JavaScript SDK

**Comment by ribsthakkar** [comment]
> @ribsthakkar Can you open an issue on the Java repo? https://github.com/Azure/azure-cosmosdb-java This one is for our older JavaScript SDK
Just did:
https://github.com/Azure/azure-cosmosdb-java/issues/180
