### ISSUE TITLE
ReplaceDocument RequestOptions object documentation may not be correct

### ISSUE THREAD

**Issue by alex-gadea** [Azure/azure-documentdb-node#206]
According to the documentation, I should pass an object that looks like

`{ accessCondition: { type: "IfMatch", condition : "someEtag" }}`

If I pass the above object in a ReplaceDocument command as the option value, it seems to have no effect.  However, if I instead send the options object as so:

`{ etag: "someEtag" }`

ReplaceDocument will return an error if the etags do not match.

It would seem something is out of whack with the documentation.

**Comment by kirankumarkolli** [comment]
@srinathnarayanan  please look into this.

**Comment by srinathnarayanan** [comment]
Hi @alex-gadea , can you please elaborate on the issue? What do you mean by no effect?
The current behaviour is that when you use 
{ accessCondition: { type: "IfMatch", condition : MATCHING_ETAG }}
as the requestOption value, the replace operation will go through and if you use a non matching etag, the replace operation will throw a 412 Precondition failed error.

However using just 
{ etag: "someEtag" }
will have no effect and the replace operation will proceed as if no precondition has been specified.

**Comment by srinathnarayanan** [comment]
I am closing this issue for now. Feel free to reopen it if this is an issue you are still running into. Thanks!
