### ISSUE TITLE
Request charge missing when using queryExecutionContext

### ISSUE THREAD

**Issue by markusahlstrand** [Azure/azure-documentdb-node#207]
We moved back from our fork as the queryExecutionContext now seemed to include the request-charge. There does however seem to be a fairly common case when you're querying across partitions that most of the request charges are lost. I would guess that any queries that doesn't return any items don't make it as they're not tied to an item?
Is there a way to get around this with the current version of the sdk? From my perspective I would ideally like to know how many queries were executed and total request charge, is this something that could be added to the mergeHeaders in the headersUtils file?

**Comment by markusahlstrand** [comment]
@moderakh if we do a PR for this, could we count on getting it reviewed fairly soon?

**Comment by moderakh** [comment]
@markusahlstrand with recent changes, in cross partition query `mergeHeaders` sums up the request charges and eventually the aggregated request charge will be passed to the callback which was registered with `queryIterator.executeNext(callback(err, resources, headers))`

I am trying to understand your question. Are you seeing that still request charge is not available to your callback for some scenarios?

**Comment by markusahlstrand** [comment]
Ok, I'll give an example.

If we make the following query to the sdk...
`SELECT TOP 10 e FROM shows e WHERE e[\"type\"]= @e_type ORDER BY e.created ASC`
.. I get 282.99 Requets Units back from the the first set of headers in the queryExcuctionContext.
All the other headers are 0.

If I on the other side do a console log in the headersUtil I get the following output:
```
0
0
0
11.79
0
24.22
0
34.9
0
47.45
0
58.71
0
69.91
0
80.50999999999999
0
91.83999999999999
0
102.63999999999999
0
114.55999999999999
0
125.65999999999998
0
137.26
0
148.13
0
158.35999999999999
0
169.39
0
180.07
0
191.31
0
202.73
0
214.92999999999998
0
227.58999999999997
0
239.22999999999996
0
250.23999999999995
0
261.50999999999993
0
272.5399999999999
282.9899999999999
282.9899999999999
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
```

If I remember correctly from when I had a look at it this is because the headers are attached to the results in the queryIterator, and since the response from the first partition is sufficient to return 10 results only those headers will be returned.

As we're currently in an optimisation phase of our cosmos-wrapper (it starts to get a bit expensive..) we need to know exactly where we are spending our resources units.

**Comment by markusahlstrand** [comment]
I got fooled by that the mergeHeaders keeps adding the charge in the headers object. It does indeed seem to work correctly. 

Thanks!
