### ISSUE TITLE
DocumentClient Configuration Using Environment Variables

### ISSUE THREAD

**Issue by graham-sportsmgmt** [Azure/azure-documentdb-node#209]
Could we please have the DocumentClient check the environment variables for its configuration?  It's no big deal to write the configuration out using process.env, but the other Azure products seem to be moving in this direction.

For example, the Azure Storage sdk looks for these:

AZURE_STORAGE_ACCOUNT and AZURE_STORAGE_ACCESS_KEY, or AZURE_STORAGE_CONNECTION_STRING.

**Comment by moderakh** [comment]
@graham-sportsmgmt  I think these environment variables are meant to be used in azure-xplat-cli not the SDK.

**Comment by graham-sportsmgmt** [comment]
Why then do other Azure SDK's use this method?  

https://github.com/Azure/azure-storage-node

It is also one of the 12 Factors used in SaaS best practices:

https://12factor.net/
