### ISSUE TITLE
Multi-bytes characters in document may become ���

### ISSUE THREAD

**Issue by yi-wan** [Azure/azure-documentdb-node#211]
I found an issue in our product that some Chinese characters may become ��� from time to time. It turns out it's due to the sdk is getting chunked **binary** data from the server and concatenating them as **string** together.
https://github.com/Azure/azure-documentdb-node/blob/eba6c2e25609b319a9fb6348fdd1a75d18a4bc2e/source/lib/request.js#L78

Since our document contains some unescaped Chinese characters, when a chunk happens to end in the middle of such a character, the result becomes ���.

We have workaround this issue by escaping all non-ASCII characters when inserting them, but I think it can be a more difficult issue if the source DB is not owned by the consumer.

**Comment by moderakh** [comment]
@yi-wan which version of DocumentDB Node.js sdk and which version of Node.js Platform are you using?

**Comment by yi-wan** [comment]
It's SDK version 1.11.0 and node.js version 6.9.1

**Comment by moderakh** [comment]
Your SDK version is a few versions behind. Please upgrade.

Unicode handling issue has already been adressed. Plz see the change log section for  1.12.2 here:
https://github.com/Azure/azure-documentdb-node/blob/master/changelog.md

**Comment by moderakh** [comment]
Plz feel free to re open the issue if upgrading to the latest version of SDK doesn't fix your issue.

**Comment by yi-wan** [comment]
Thank you. The issue is fixed after I upgraded to the latest version. The type of 'chunk' is now string, too.
