### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by andrehsmendes** [Azure/azure-documentdb-node#214]
Hello,

How is the pagination working with the node sdk?

I've been trying to do pagination using FeedOptions on queryDocuments but i cant get it to work and i cant find any references to this matter either.

Can someone point me in the right direction?

Thank you

**Comment by moderakh** [comment]
hi @andrehsmendes 
please take a look at this:
https://github.com/Azure/azure-documentdb-node/blob/master/source/test/crossPartitionTests.js#L409-L432

**Comment by andrehsmendes** [comment]
@moderakh thank you. 
I was really helpful.

I think that Microsoft could have done a better work on the documentation for nodejs sdk. Some things are really difficult to find.

thx again.
