### ISSUE TITLE
The continuation token specified in the request is malformed

### ISSUE THREAD

**Issue by andrehsmendes** [Azure/azure-documentdb-node#215]
Hey,

I'm really having a hard time trying to make pagination work.

This is what i have:
```javascript
find: function (querySpec) {
        var self = this;
        return new Promise((resolve, reject) => {
            var options = {
                maxItemCount: 2
            }
            var query = self.client.queryDocuments(self.collection._self, querySpec, options);
            query.executeNext(function (err, results, headers) {
                if (err) {
                    reject(err);
                } else {
                    self.continuation = headers['x-ms-continuation'];
                    resolve({ 'results': results, 'resource': headers['x-ms-resource-usage'] });
                }
            })
        });
    },
```
```javascript
nextPage: function () {
        var self = this;
        console.log(this.continuation)
        return new Promise((resolve, reject) => {
            var options = {
                maxItemCount: 2
            }
            self.continuation ? options['continuation'] = self.continuation : '';
            var query = self.client.readDocuments(self.collection._self, options);
            query.executeNext(function (err, results, headers) {
                if (err) {
                    reject(err);
                } else {
                    resolve({ 'results': results, 'resource': headers['x-ms-resource-usage'] });
                }
            })
        });
    }
```

**Continuation Token:**
`{"token":"-RID:K0JYAKIH9QADAAAAAAAAAA==#RT:1#TRC:2","range":{"min":"","max":"FF"}}`

**Return Error:**
`{ code: 400,
  body: '{"code":"BadRequest","message":"Message: {\\"Errors\\":[\\"The continuation token specified in the request is malformed. Please re-run the query without it and iterate.\\"]}\\r\\nActivityId: 9e04278a-3808-4a59-8e63-dae191ef3519, Request URI: ...."}',
  activityId: '9e04278a-3808-4a59-8e63-dae191ef3519' }`

What m'i doing wrong?

**Comment by kirankumarkolli** [comment]
@srinathnarayanan could you please take look at this?

**Comment by andrehsmendes** [comment]
Hey, is this repo still alive? @srinathnarayanan

**Comment by srinathnarayanan** [comment]
Hi @andrehsmendes it is. What issues are you running into and where is you endpoint located?

**Comment by andrehsmendes** [comment]
Hey @srinathnarayanan 

I'm trying to do pagination with CosmosDB. I'm not entirely sure how to achieve this with CosmosDB but i saw in some test files using continuation token to do so.

Look my example above, this is what i'm doing to paginate my calls to the DB. 

What do you mean by where is the endpoint located?

**Comment by srinathnarayanan** [comment]
you are running a cross partition query and hence the continuation token has a range component. We do not support the use of continuation tokens to get the next page on cross partition queries. If it were a query running on a single partition, the continuation token will have only the token component, which can be used for pagination.

**Comment by andrehsmendes** [comment]
Hey @srinathnarayanan 

I'm querying one Collection and the collection is the LIMITED 10gb/ not partitioned.

**Comment by srinathnarayanan** [comment]
Hi @andrehsmendes can I know your use case? If you are trying to get pages of a fixed size, setting the maxItemCount in the options would be enough. The queryIterator returned will take care of the continuation token for subsequent 'executeNext()' operations.

**Comment by andrehsmendes** [comment]
@srinathnarayanan 

I see. makes sense. 

Another question that i have is, how would you control the pagination? for example:

PAGE-1   PAGE-2   PAGE3

Going from page 1 to 3 and from 3 to 1.

Thank you for your help so far.

**Comment by srinathnarayanan** [comment]
The first time you are accessing the results, you will have to go in sequence since you will not know the continuation token. Once you have accessed a page, you can cache/ save the continuation token (and perhaps map it to the page number). For subsequent queries, you can go from page 1 to page 3 or vice versa using these cached continuation tokens.

**Comment by moderakh** [comment]
I am closing this for now as the initial problem is answered. please feel free to open an issue if you face problem.

**Comment by guptakumartanuj** [comment]
I am just running into the same but for the cross partition query. So I am curious to know  how to support pagination in my application when I have data across the partitions.

**Comment by goodisontoffee** [comment]
@srinathnarayanan is it still the case that presenting a continuation token for a cross-partition query is not supported? I'm struggling to find anything that makes this clear in the documentation and before I start rewriting our code, I'd like to make sure I'm not wasting my time.

Thanks in advance.

**Comment by rahul230691** [comment]
@srinathnarayanan is continuation token still not supported for a cross-partition query? Sometimes I get "**the continuation token specified in the request is malformed**" exception or sometimes I get "**Invalid format for continuation token**" exception. Help please @kirankumarkolli
