### ISSUE TITLE
1.14.0 is broken on Linux

### ISSUE THREAD

**Issue by joaomoreno** [Azure/azure-documentdb-node#217]
There' s bad require call in https://github.com/Azure/azure-documentdb-node/blob/master/source/lib/documentclient.js#L36:

```js
SessionContainer = require("./SessionContainer");
```

The file is actually called `sessionContainer.js`, so the require is using the wrong casing. This breaks in every case sensitive FS.

**Comment by benc-uk** [comment]
I see this is fixed in a recent PR, any idea when this will get released and be avail on NPM? This is a blocker for me
