### ISSUE TITLE
v1.14 stops me connecting to my Cosmos emulator locally

### ISSUE THREAD

**Issue by rossvernal** [Azure/azure-documentdb-node#219]
I get the error: 

"Error Invalid API version. Ensure a valid x-ms-version header value is passed"

There is no update to the emulator.

Dropping to 1.13 stops the issue from happening.

**Comment by srinathnarayanan** [comment]
This SDK version requires the latest version of Azure Cosmos DB Emulator available for download from https://aka.ms/cosmosdb-emulator. We will update the changelog to reflect the same, shortly

**Comment by rossvernal** [comment]
@srinathnarayanan thanks - that worked. Wish the Cosmos Emulator would auto-update, but that's another question for another day!
