### ISSUE TITLE
Impossible to delete documents that have no partition key.

### ISSUE THREAD

**Issue by tony-gutierrez** [Azure/azure-documentdb-node#222]
Apparently in the .NET sdk there is a constant for "Undefined Partition Key", but no such constant seems to exist in this sdk. 

So that makes it impossible to delete (or update) a document that has no partition key.

**Comment by srinathnarayanan** [comment]
Hi @tony-gutierrez The undefined partition key in the .NET SDK is converted to an empty JSON while being sent at a http request. You can replicate this behavior on the Node sdk using the following :  

    client.deleteDocument( DOCUMENT_LINK , { partitionKey: {} }, function (err, document) {
            console.log("document deleted")
        })

**Comment by tony-gutierrez** [comment]
Ill try it.

**Comment by srinathnarayanan** [comment]
I am closing this as the initial query has been addressed. Please feel free to reopen it if you have any followup. Thanks!

**Comment by tony-gutierrez** [comment]
Did it make it to any documentation?
