### ISSUE TITLE
Have a way of returning the aggregate x-ms-request-charge header from the QueryIterator.toArray() call

### ISSUE THREAD

**Issue by limeybastow** [Azure/azure-documentdb-node#226]
For performance logging, it would be nice to be able to be able to retrieve the aggregate request charge from the QueryIterator.toArray() call.  Currently the last response headers are returned in the callback if an error occurs, however nothing is returned on a successful call.  A quick and dirty method might be to collect all of the headers in an array and return those in the callback but that may be overkill as in general the only interesting piece of info is the request charge so another would be to return a generated header that contains the aggregate request charge.

**Comment by srinathnarayanan** [comment]
Hi @limeybastow You can use the QueryIterator.forEach() call for that very purpose. For example, if you want to read 5 documents per page, you can use the following snippet : 

var queryIterator = client.queryDocuments(COLLECTION_LINK, "Select * from c", { maxItemCount: 5 });
        var count = 0;
       
        queryIterator.forEach(function (err, doc, headers) {
            if (doc === undefined) {
                done();
            }
            count++;
            if (count % 5 == 1) {
                console.log(headers['x-ms-request-charge'])
            }
            console.log(doc);

        });

The cumulative header (including total RU cost) for each fetched page is contained in the response corresponding to the first element of that page.

**Comment by srinathnarayanan** [comment]
I am closing this as the initial query has been addressed. Please feel free to reopen it if you have any followup. Thanks!
