### ISSUE TITLE
PreferredLocations ignored

### ISSUE THREAD

**Issue by beneuto** [Azure/azure-documentdb-node#228]
I have a Cosmos database replicated over 2 regions.   Client is defined as below.   However, no query is ever sent to Australia Southeast.

```
var connectionPolicy = new documentdb.DocumentBase.ConnectionPolicy();
connectionPolicy.PreferredLocations = ['Australia East', 'Australia Southeast'];
connectionPolicy.EnableEndpointDiscovery = true;

var client = new documentdb.DocumentClient(host, {masterKey: roKey}, connectionPolicy );
```

**Comment by srinathnarayanan** [comment]
Hi @beneuto. Couple of questions. Which operations are you running? Which are the read locations and which are the write locations, as configured for your account ?

**Comment by beneuto** [comment]
I am only using queryDocuments.   Australia East is write and Australia Southeast is read.

**Comment by christopheranderson** [comment]
(Sorry for the latency here)

You need to remove the write region from preferred regions. It will use any of the preferred regions. Remove Australia East and reads should go to Australia Southeast.

```javascript
connectionPolicy.PreferredLocations = ['Australia Southeast'];
```

**Comment by beneuto** [comment]
That doesn't work.   It still goes to the write region.   Regardless, the aim is to balance load over both regions.

**Comment by GustavoMoreiraPT** [comment]
Hi @beneuto, @srinathnarayanan and @christopheranderson 

Just saw your post.
Did you find anything about this issue?
I have a project where I am using Cosmos emulator for developing purposes.
With EnableEndpointDiscovery set to true, after a first successful request, if I turn of the emulator, the request is taking 4/5 minutes before timing out.
I need this property set to true in live environment.
Is this only happening in the emulator?
Thank you,
Gustavo Moreira
