### ISSUE TITLE
Use real error objects in error fields for callbacks

### ISSUE THREAD

**Issue by lightsofapollo** [Azure/azure-documentdb-node#23]
This is particularly bad when trying to debug issues in tests via frameworks (like mocha). 

Example:

https://github.com/Azure/azure-documentdb-node/blob/master/core_sdk/lib/request.js#L46

Ideally this could use real error object with useful message then attach the code, etc... (See superagent for some examples of how to do this)

**Comment by ryancrawcour** [comment]
if you would like to submit a PR for this change we'd gladly review your change.
