### ISSUE TITLE
Promise support

### ISSUE THREAD

**Issue by benc-uk** [Azure/azure-documentdb-node#231]
Are there plans to introduce a Promise based version of the library? 

They have been in language since 2015 and now with async/await they are core part of how people write modern JavaScript

**Comment by gluwer** [comment]
There is a https://github.com/Azure/azure-documentdb-node-q. Not using it personally so cannot tell much about it but it exists :)

**Comment by amitbend** [comment]
+1 for that.

**Comment by jcormont** [comment]
You can also take a look at [documentdb-typescript](https://github.com/jcormont/documentdb-typescript). No TypeScript required if you're using modern JS and async/await.

**Comment by christopheranderson** [comment]
This work is done in the v2 API which will GA later this year. You can follow that work on the new repo: https://github.com/Azure/azure-cosmos-js

**Comment by benc-uk** [comment]
Great! Thanks @christopheranderson . From even a quick 5 minute glance I can see the new API and library is huge improvement
