### ISSUE TITLE
Missing documentation for proxy settings

### ISSUE THREAD

**Issue by yeya** [Azure/azure-documentdb-node#243]
[This PR](https://github.com/Azure/azure-documentdb-node/pull/220/commits/3952dfb89a23023d0bae46c704049b45cf5547e3) has been already merged, but I can't find any documentation how to use or initialize the `connectionPolicy` Object 

How should I use it?

**Comment by moderakh** [comment]
Hi @yeya 

You can use this code sample for setting proxy endpoint in ConnectionPolicy and using it:

setting proxy in connectionpolicy:
https://github.com/Azure/azure-documentdb-node/blob/master/source/test/proxyTests.js#L53-L55

instantiating DocumentClient with the given policy:
https://github.com/Azure/azure-documentdb-node/blob/master/source/test/proxyTests.js#L60

**Comment by yeya** [comment]
#solved
Thanks.
It's really missing in the documentation.

**Comment by moderakh** [comment]
@yeya thanks for reporting it. You are right. We will fix the documentation.
