### ISSUE TITLE
Need way to set/add to user agent

### ISSUE THREAD

**Issue by StephenWeatherford** [Azure/azure-documentdb-node#244]
(I don't think this is the same request as #234)

I need a way to set the user-agent for the document client.  Right now I can do this by modifying defaultHeaders directly on the client, but this isn't exposed in the Typescript definition, so I'm not sure if it just needs to be added, or if this would be relying on internal implementation details.  Thanks.

**Comment by srinathnarayanan** [comment]
@christopheranderson can you please take a look at this? Thanks.

**Comment by christopheranderson** [comment]
The way to do this today is to set it on the documentClient after it is created (aka monkey patch).

```javascript
const client = new DocumentClient(...);
client.requestAgent = new https.Agent(...);
```

In the next version of the SDK, https://github.com/azure/azure-cosmos-js, this will be available in the constructor so you don't have to monkey patch.
