### ISSUE TITLE
Documentation should show how to connect to an existing database

### ISSUE THREAD

**Issue by geuis** [Azure/azure-documentdb-node#34]
I'm working through the available node.js documentDB documentation today. Creating a database is clearly demonstrated, but nowhere that I can find is connecting to an existing database described.

There are mentions of needing the databaseLink property, but again it is not described how to get this from Azure.

Edit: 

This is one solution that I've been able to piece together, though I am by no means certain this is the best way.

    var ddbName = 'testDb';
    
    var documentClient = require('documentdb-q-promises').DocumentClientWrapper;
    var ddb = new documentClient(ddbUrl, {masterKey: ddbPrimaryKey});
    
    var db = ddb.queryDatabases('SELECT * FROM root r WHERE r.id = "' + ddbName + '"');
    
    db.nextItemAsync().then(function nextItem (result) {
      if (db.hasMoreResults() && result['id'] !== ddbName) {
        db.nextItemAsync().then(nextItem);
      } else {
        // has a match, do stuff
        console.log(result);
      }
    });

**Comment by aliuy** [comment]
Looks like you got it!

You can extend that logic even further to include some logic around gettting a database, and creating one if one does not exist. Something along the lines of:

```js
function getOrCreateDatabase(databaseId, callback) {
  var querySpec = {
    query: 'SELECT * FROM root r WHERE r.id=@id',
    parameters: [{
      name: '@id',
      value: databaseId
    }]
  };
  client.queryDatabases(querySpec).toArray(function(err, results) {
    if (err) {
      handleError(err);
    }

    if (results.length === 0) {
      console.log('Database \'' + databaseId + '\'not found');
      var databaseDef = {
        id: databaseId
      };

      client.createDatabase(databaseDef, function(err, created) {
        if (err) {
          handleError(err);
        }

        console.log('Database \'' + databaseId + '\'created');
        callback(created);
      });
    } else {
      console.log('Database \'' + databaseId + '\'found');
      callback(results[0]);
    }
  });
}
```

I'll admit our samples are a bit buried and we should do a better job surfacing them.

You can find more samples in the `/samples` directory in this repo: https://github.com/Azure/azure-documentdb-node/tree/master/core_sdk/samples
