### ISSUE TITLE
Stream support ?

### ISSUE THREAD

**Issue by asafyish** [Azure/azure-documentdb-node#35]
Hi,

Is there stream support ? Is it planned ?
It's really easy to get a "process out of memory" exception without it.

**Comment by nomiero** [comment]
Hi asafyish,

There is support for creating attachment using a stream using the API createAttachmentAndUploadMedia, but it's not supported for documents.
The maximum document size is 512k, so you shouldn't be getting out of memory for creating documents.
Can you give more clarification on what are you trying to do that caused 'process out of memory' ? 
Thanks.

**Comment by asafyish** [comment]
Hi,
Sorry for the delay.

I am not referring to attachments/single documents,
Lets say I am using the queryDatabases api and the result of that query is 200000 tiny docs that together, are around 3 gb, how can I iterate over it ? If I call toArray on it, node.js will crash.

**Comment by nomiero** [comment]
you only use toArray if you know that the number of documents is small.
If you want paging you instead use executeNext which will return the next page and you combine that with the calls of hasMoreResults to know when there are no more results.
And when you create the query, you can control the page size with the maxItemCount option.
You can look at the executeNext and hasMoreResults to see the usage
https://github.com/Azure/azure-documentdb-node/blob/master/core_sdk/test/test.js#L986

**Comment by asafyish** [comment]
Yeah that can solve our problem, but I don't think it's the elegant solution, I mean, In node.js, if you want to process large amount data, the usual mechanism for that is, using stream, which allows you to pipe data in all sort of ways and use any number of higher-level functions over it, such as [highlandjs](http://highlandjs.org)

**Comment by nomiero** [comment]
Thanks for the feedback.
It's in our plan to make the non intuitive node apis easier, for now the current apis for executeNext and hasMoreResults are core apis that can work with paging. If you are going to use them a lot, it would be good to add a wrapper around these functions to make things easier.
