### ISSUE TITLE
Auto-retry after XXXms on 429

### ISSUE THREAD

**Issue by molant** [Azure/azure-documentdb-node#39]
It will be great if there were an option to autoretry if a 429 error happens. The documentation about this is a bit difficult to find and AFAIK the C# SDK is capable of handle this.

**Comment by ryancrawcour** [comment]
Yes, you are right, it would be great. We'd be very happy to receive a PR from you for this if you wish :)

**Comment by molant** [comment]
Happy to do a PR. Do you mind pointing me to the docs where it explains a bit more the 429 error, the headers and the values it can have (is it in ms, secs, etc.?). I haven't found anything and reproducing this consistently is not easy.
Also, why has this issue been closed? I've read the [contribution guidelines](http://azure.github.io/guidelines.html) and it clearly says I can request a new feature via a GitHub issue. Also usually PR are linked to issues (what's the point in submitting a code change if there isn't "a problem").

Thanks

**Comment by ryancrawcour** [comment]
To be honest, I hit the wrong button. I hit the "Close and comment" button. Sorry, been a long day :)

**Comment by ryancrawcour** [comment]
I think this would be a great addition to this and happy to work with you on getting it done. 
I will collect material on the 429s and how to handle them and will add to this issue to track.

**Comment by molant** [comment]
I bet, congrats on going GA!

**Comment by aliuy** [comment]
Hey guys - here's some things to help you guys get started!

The queryDocuments() method returns a queryIterator, which has methods like toArray() and executeNext().

See https://github.com/Azure/azure-documentdb-node/blob/master/core_sdk/lib/queryIterator.js

I just whipped up a snippet to help you get started with executeNext() and 429's. It might be better to implement toArrayWithRetry(), and have it either console.log() or return some aggregated query stats (# of iterations, RU charge, etc).

```js
var queryIterator = documentClient.queryDocuments(collection._self, query);
executeNextWithRetry(yourCallback);

function executeNextWithRetry(callback) {
    queryIterator.executeNext(function(err, results, responseHeaders) {
        if(err && err.code === 429 && responseHeaders['x-ms-retry-after-ms']) {
            
            console.log("Retrying after " + responseHeaders['x-ms-retry-after-ms']);
            
            setTimeout(function() {
                executeNextWithRetry(callback);
            }, responseHeaders['x-ms-retry-after-ms']);
            
        } else {
            callback(err, results, responseHeaders);
        }
    });
}
```

**Comment by molant** [comment]
Thanks!
For the logs, are you using any environment variable/module to check if an output has to be done? Also, any reliable way for me to get a 429?
I'm refactoring right now how we store the data in a project with documentdb but I'd like to start working on this sometime next week. Is there an established style guide? Haven't seen any linting task or an [.editorconfig](http://editorconfig.org/) file to make authoring easier. I could look the current code and add those as a separate PR if you are OK.

**Comment by aliuy** [comment]
The SDK doesn't output any logging today (something we intend to fix). Using an client or environment variable to set log levels would be a great idea.

You can reliably reproduce a 429 by sending a request after consuming all the provisioned request-units in a collection. The easiest way to do this is to set the performance tier of a collection to the lowest available tier (S1), and then bombarding the collection with an expensive query (e.g. a query that scans and returns large amount of large documents). Assuming you have a fair amount of documents in the collection already, firing off a lots of plain `select * from c` queries without any predicates will do the trick.

As for linting... I love linting! I'd be very appreciative and am more than happy to work with you on this :grinning:

**Comment by molant** [comment]
@aliuy I've opened #40 to discuss the linting process.

**Comment by shpros** [comment]
I stumbled on this issue while looking for information on a related issue. We're getting 429s not only from creating documents, but also from calling `queryCollections` and `queryStoredProcedures`. We would handle the retry ourselves, but we're using the promises flavor, which doesn't return the headers with the error. It would be great to have headers returned on error in the promises flavor. Currently, all of the `deferred.reject()` calls pass only the error, and swallow the headers, so we don't get the x-ms-retry-after-ms header or any other headers. See e.g. https://github.com/Azure/azure-documentdb-node/blob/master/q_promises_sdk/documentclientwrapper.js#L16

**Comment by ryancrawcour** [comment]
could we create a new issue for this specific issue so that we can track them separately.

**Comment by shpros** [comment]
@ryancrawcour  Does this issue #39 include the promises wrapper too, or should that also be a separate issue?

**Comment by molant** [comment]
If you use [bluebird to promisify](https://github.com/petkaantonov/bluebird/blob/master/API.md#promisification) the library it should automagically work (that is what I have in my project).

**Comment by ryancrawcour** [comment]
@molant this is why we split q promises from the core driver, to allow customers to use whichever promises framework they would like.

**Comment by molant** [comment]
@ryancrawcour and I think it is a great idea :)

**Comment by ryancrawcour** [comment]
@shpros probably best to do a separate issue so we can track these separately

**Comment by ryancrawcour** [comment]
@molant regarding your comment of "use bluebird to promisify" is this a once-off operation to generate the bluebird promise aware wrapper?

**Comment by molant** [comment]
@ryancrawcour yes although it will modify the object you pass and add new methods that return promises. More info in https://github.com/petkaantonov/bluebird/blob/master/API.md#promisepromisifyallobject-target--object-options---object

**Comment by shpros** [comment]
"@shpros probably best to do a separate issue so we can track these separately" 
@ryancrawcour I'm not sure why you're responding to this again. See [upthread](https://github.com/Azure/azure-documentdb-node/issues/39#ref-issue-76055224); we created #45 in May and you already merged it.

**Comment by rnagpal** [comment]
@molant @shpros  Node.js 1.9.0 now has the auto-retry behavior for 429s.
