### ISSUE TITLE
Add a linting task to the project so contributions follow the same standard

### ISSUE THREAD

**Issue by molant** [Azure/azure-documentdb-node#40]
I normally use [ESLint](http://eslint.org) for code quality, [JSCS](http://jscs.info/) for code style (spaces, etc.) as a [grunt-tasks](http://gruntjs.com/) during the build process and then an [.editorconfig](http://editorconfig.org/) file so my editor automatically picks if I should be using tabs or spaces, how many, etc.

We could probably add a test task to the gruntfile to use the code you already have.

**Comment by molant** [comment]
@aliuy I think I'll submit a PR with the basic setup with the rules I currently have in my projects and then you can tweak the options to follow your style guide if that sounds ok.

**Comment by aliuy** [comment]
That sounds great!

I'm a bit new to ESLint and JSCS (I've mostly used JSHint for my projects). Mind giving me a little background knowledge? On the surface, it looks like ESLint also supports rules for styling. Is there an advantage for using both?

**Comment by molant** [comment]
I think the plan for ESLint is to have the same rules as JSCS but when I started they weren't implemented yet so I right now I'm using JSCS to validate all my spacing is the right one and the other to make sure I have consistent returns, no shadow variables, etc. Haven't check recently if they have added all the style rules.
I also think that ESLint gives a lot more flexibility and supports more things than JSHint (JSX, ES6 for example).

**Comment by molant** [comment]
Now that http://dev.modern.ie is released I have some time to work on this. I'll probably do a PR this week if you are still interested :)

**Comment by aliuy** [comment]
Yes, we'd love that! :+1:

**Comment by shipunyc** [comment]
Thanks.
