### ISSUE TITLE
client.createDocumentAsync error?

### ISSUE THREAD

**Issue by IrisClasson** [Azure/azure-documentdb-node#41]
I might just be very tired, but I noticed some unexpected behavior I though I would share to check my sanity/lack of sleep. 

If I call : client.createDocumentAsync(collection._self, doc); the promise chain is broken and I get an error that automatidIdgeneration can't be read on undefined. I'm not passing in options as you can see.

However, if I call: client.createDocumentAsync(collection._self, doc,{}); it works fine and continues.

The original call, client.createDocument(collection._self, doc, function (err,doc){}); does not return an error with the same params. From the tests in the core SDK I can't see that  {disableAutomaticIdGeneration: false} is required.

Anyways, great job- thanks for wrapping up the client neatly. Thumbs up!

**Comment by nomiero** [comment]
Hi Iris,

Thanks for reporting the issue. There is a bug now in the promise wrapper that happens with createDocumentAsync without passing options and without having an id property in the document ( I guess that's the case you have and it's the case not covered in tests ).
A fix for this issue will be available with the next release but for now you can continue with the work around you have.

**Comment by ryancrawcour** [comment]
closed with release of 1.0.1
