### ISSUE TITLE
Promises wrapper does not include headers with error

### ISSUE THREAD

**Issue by shpros** [Azure/azure-documentdb-node#45]
We're getting 429s from methods as various as createDocument, queryCollections, and queryStoredProcedures. Until #39 is addressed, we would like to handle the retry ourselves, but we're using the promises flavor, which doesn't return the headers with the error. It would be great to have headers returned on error in the promises flavor. Currently, all of the deferred.reject() calls pass only the error, and swallow the headers, so we don't get the x-ms-retry-after-ms header or any other headers. See e.g. https://github.com/Azure/azure-documentdb-node/blob/master/q_promises_sdk/documentclientwrapper.js#L16

**Comment by shpros** [comment]
We'd like to fork and take a crack at this if that's ok.

**Comment by ryancrawcour** [comment]
Absolutely. We'd love to accept contributions from the community.

**Comment by shpros** [comment]
Great, we should have a PR for you soon.

**Comment by BillAtPros** [comment]
PR #46 submitted.

**Comment by ryancrawcour** [comment]
Thanks, we'll take a look shortly.

**Comment by BillAtPros** [comment]
Bump.

**Comment by ryancrawcour** [comment]
Sorry for the delay in getting to this. I will chase up the reviewers now.

**Comment by ryancrawcour** [comment]
Closed with [PR #46] (https://github.com/Azure/azure-documentdb-node/pull/46)
