### ISSUE TITLE
current property conflicts with method current()

### ISSUE THREAD

**Issue by siritsch** [Azure/azure-documentdb-node#49]
It is not possible to call the current() method of DocumentClient. If you try to do that an exception is thrown saying that current is not a method. The current () method should be renamed e.g. to currentElement()

**Comment by nomiero** [comment]
There is no current() method in DocumentClient, do you mean the queryIterator returned by the query or readFeed method ?

**Comment by siritsch** [comment]
Sorry. I mean the current() method of QueryIterator. This class also has a property current, which stores the index of the current object in the resource array.

**Comment by nomiero** [comment]
Makes sense, thanks for notifying us about the bug, we will get it fixed as soon as possible

**Comment by ryancrawcour** [comment]
This has now been fixed.
