### ISSUE TITLE
Why does the callback function of the forEach method of class QueryIterator take two arguments?

### ISSUE THREAD

**Issue by siritsch** [Azure/azure-documentdb-node#50]
The callback function of the QueryIterator has two arguments an error object and an element object. It does not make sense to pass an error object for each element. Either the query has been successful the always null or undefined would be passed as error object or the query failed then there are no objects to return. In the case of a failed query forEach could throw an exception.

When first using the forEach method I implemented a callback method with only one parameter which was the expected element. I wondered why I always received undefined. After stepping through the debigger I found that there are two arguments passed to the callback.

**Comment by aliuy** [comment]
To clarify on the existing behavior: the forEach() method can cause the QueryIterator to fetch more pages. If the call to fetch more pages fails (e.g. the request got throttled), an error is passed back to the callback.

**Comment by siritsch** [comment]
So in this case the exceptual use case (request gets throttled) has been made a rule. In my opinion it would have been better to throw an exception in case an error occures when fetching more pages. Even, if the decision is to pass an error object it would have been better to pass it as the second argument.

**Comment by siritsch** [comment]
If the request gets throttled only passing back the error object is not sufficient. There should be also a responseHeader with a x-ms-retry-after-ms property.
