### ISSUE TITLE
PR 53 reverts PR 46

### ISSUE THREAD

**Issue by shpros** [Azure/azure-documentdb-node#55]
#46 was merged into mainline, but the merge of #53 reverted those changes. Intentional, or bad merge conflict? #46 was a fix for #45, which is mentioned in the [changelog for 1.0.2](https://github.com/shipunyc/azure-documentdb-node/blob/master/core_sdk/changelog.md).

**Comment by ryancrawcour** [comment]
will investigate

**Comment by shipunyc** [comment]
I will reapply #46

**Comment by ryancrawcour** [comment]
turns out our internal source repository was out of sync with GitHub repo. our mistake. sorry about that.

**Comment by shpros** [comment]
Thanks for re-applying. Also thanks for fixing "occured" -- that one was driving me nuts but I didn't want to make that change in a totally unrelated PR.

**Comment by ryancrawcour** [comment]
this has been fixed. 1.0.3 pushed to npm.
