### ISSUE TITLE
RequestEntityTooLarge

### ISSUE THREAD

**Issue by mauricionr** [Azure/azure-documentdb-node#65]
I'm trying to update a document in my DocumentDB, but i've got this error

RequestEntityTooLarge

{"code":"RequestEntityTooLarge","message":"Message: {\"Errors\":[\"Request size is too large\"]}\r\nActivityId: guid, Request URI: /apps/guid/services/guid/partitions/guid/replicas/id"}

How can i solve this?

Thanks!

**Comment by ryancrawcour** [comment]
I suspect this is because you attempted a request that was too large. Usually this happen when tue document you are trying to save exceeds the allowed document size. 

Try minifying your JSON, or create smaller document.

**Comment by mauricionr** [comment]
Thanks, I will try.
