### ISSUE TITLE
Weird partial encoding errors

### ISSUE THREAD

**Issue by petetnt** [Azure/azure-documentdb-node#68]
I am using `documentdb` through [a8m/doqmentdb](https://github.com/a8m/doqmentdb) and I am running into this weird encoding issue.

I have a document that contains some properties with a word with some characters with umlauts (mainly ä and ö, which are quite common in the finnish alphabeth) as the value.

Occasionally (let's say 5% of the time) when a FIND a document, certain letter, ö, is not correctly encoded, which results in this:

```
[ 
 {
 foo: [
   "Läht��laukaus"
  ]
 }
]
```

When the correct form should be:

```
[ 
 {
 foo: [
   "Lähtölaukaus"
  ]
 }
]
```

I couldn't replicate it with Query Explorer on `https://portal.azure.com/` and `doqmentdb` doesn't seem to modify the responses in any way, so something funky seems to be happening between `DocumentClient` and the DocumentDB-database itself. Using `documentdb` version 1.2.0

**Comment by ryancrawcour** [comment]
Are you saying that sometimes the same document, and the same code displays correctly and sometimes not?

**Comment by petetnt** [comment]
@ryancrawcour pretty much. Same code, same database, same collection, same (or any) document containing certain letters.

**Comment by petetnt** [comment]
I tried to debug this today but wouldn't replicate it anymore. Weird, might have been some sort of generic Node problem... closing for now, I'll reopen if I run into it again.
