### ISSUE TITLE
Retry Policy Missing

### ISSUE THREAD

**Issue by danbucholtz** [Azure/azure-documentdb-node#75]
Hello,

I have noticed that most other programming languages client's for DocumentDB have a retry policy built-in.  For example, in Java:

https://github.com/Azure/azure-documentdb-java/blob/master/src/com/microsoft/azure/documentdb/RetryPolicy.java

are there any plans or a timeline for when this will be added to the node client?

Thanks!

**Comment by ryancrawcour** [comment]
Yes. This is planned and will start soon.

**Comment by danbucholtz** [comment]
@ryancrawcour, awesome!  Any thoughts on a timeline?  We are trying to do some planning.  If it's 6 months, we'll probably roll our own retry.  If it's a few weeks, we'd wait.  Thanks for all your great work!

**Comment by Jacob-McKay** [comment]
+1 the retry policy found in your other libraries is super convenient!

**Comment by ryancrawcour** [comment]
@danbucholtz it won't be 6 months. I'm aiming for more like 4-6 weeks.

**Comment by ryancrawcour** [comment]
@Jacob which libraries are you referring to? DocumentDB libraries or other Azure libraries?

**Comment by danbucholtz** [comment]
@ryancrawcour, sounds good on the 4-6 weeks.  I will just wrap the calls in my own retry policy for now.

Thanks!

**Comment by rnagpal** [comment]
@danbucholtz @Jacob-McKay : Node.js 1.9.0 has the auto-retry built in for 429s. Let us know if you were looking on retrying on any other error code and we can evaluate.

**Comment by Jacob-McKay** [comment]
@rnagpal originally I was thinking of retrying on codes like 500, but in practice the only error codes I have seen are 429 and 404.  You've got the 429 case, and on 404 I would not retry :P

**Comment by rnagpal** [comment]
@Jacob-McKay : You shouldn't retry on 500s(Internal Server Error) as that can be a valid error code indicating some problem. 404(Resource Not Found) is also a non-retryable error.

429(Request Rate Too Large) is one of the most common retryable error code that makes sense and hence we added the support for just that.

**Comment by tony-gutierrez** [comment]
There is no sample or documentation on how to use the retry policy?
