### ISSUE TITLE
documentdb-q-promises

### ISSUE THREAD

**Issue by danbucholtz** [Azure/azure-documentdb-node#76]
Did this source code just completely go away?  We were developing against the npm module (https://www.npmjs.com/package/documentdb-q-promises).

We were developing against the module, but I see the npm package has been updated to point to this repo, and I see any references to it were blown away in this commit:

https://github.com/Azure/azure-documentdb-node/commit/581e0fcbdb1c8f63cf82f1f171170d79f2e836d

Can you shed some light?

**Comment by ryancrawcour** [comment]
I have just split this off in to its own repo. I have not, yet, updated the npm module. 

https://github.com/Azure/azure-documentdb-node-q is the new home for this wrapper.

Apologies for the confusion.
