### ISSUE TITLE
base#getAttachmentIdFromMediaId base64 Conversion issue

### ISSUE THREAD

**Issue by ronaldewatts** [Azure/azure-documentdb-node#81]
This is a NodeJS project using When uploading attachments occasionally we get the following error when fetching the image:
```
{"code":"Unauthorized",
"message":"The input authorization token can't serve the request. 
    Please check that the expected payload is built as per the protocol, 
    and check the key being used. Server used the following payload to sign: 
    'get\nmedia\n6hl2aldwbqcxagaaaaaaac4-1vo=
    \nwed, 28 oct 2015 03:48:05 gmt\n\n'\r\nActivityId: 1160f842-e8b4-4e28-aa27-a080f4d76424"}
```
Which is strange because the same master key is used throughout and many other objects, including attachments are fetched just fine.  Looking deeper into the base.js#getAttachmentIdFromMediaId I noticed it is converting my mediaId of 6hl2ALdWbQCxAgAAAAAAAC4-1VoB to 6hl2ALdWbQCxAgAAAAAAAC4+1Vo=.  What is of note here is the conversion of the "-" to a "+".  Writing a line of code to replace this back solves the problem.  I started looking at other SDKs for docdb and noticed that there is an inconsistency in this method across them.  Python for example calls out a situation between -, + and /.  Java deals with just - and /.  The Node and JS projects don't handle any of those (https://github.com/Azure/azure-documentdb-node/blob/master/source/lib/base.js#L299).

Could somebody take a look at this?  I can provide credentials to a live example if needed.

**Comment by ryancrawcour** [comment]
I will get someone to take a look at this for you. You are also welcome to submit a PR to rectify this if you like and we'll review and accept in to the SDK.

**Comment by ronaldewatts** [comment]
Thanks Ryan.  I would go the PR route, but I'm not really sure of the requirement and assume it should be consistent across all platform SDKs.

**Comment by ronaldewatts** [comment]
PR created:  https://github.com/Azure/azure-documentdb-node/pull/84

**Comment by ronaldewatts** [comment]
I'm curious if anybody has had a chance to look at PR https://github.com/Azure/azure-documentdb-node/pull/84 ?  As this problem was impacting us quite a bit I've had to basically freeze on a version with my changes in it in a fork.

CC: @ryancrawcour

**Comment by ryancrawcour** [comment]
Please verify that npm package version 1.5.3 fixes this issue

**Comment by rwatts-d3** [comment]
Will do.  Thanks @ryancrawcour .
