### ISSUE TITLE
update documentation with details of .toArray()

### ISSUE THREAD

**Issue by dwhieb** [Azure/azure-documentdb-node#83]
I was concerned that the .toArray() method of the queryIterator wasn't pulling all the results, because the documentation made it sound as though you had to use .executeNext() to retrieve batches of results. Eventually I found this note in the sample code though:

https://github.com/Azure/azure-documentdb-node/blob/ea5df70635751f6dc8f4eeb7587f820a61ce9c67/samples/DocumentDB.Samples.IndexManagement/app.js#L322

It looks like .toArray() will always return all the results, so .executeNext() isn't needed in the default scenario unless you have some other reason for using it. Do I have this right? If so, could the documentation for the .toArray() method be updated to reflect this?

**Comment by ronaldewatts** [comment]
I do think you have it right.  I worked through the same bit of confusion using the Promises version (.toArrayAsync() and .executeNextAsync()).  However, there is a x-ms-max-item-count on results retrieved in DocumentDB that caps at 1000.  I'm also interested in what happens with .toArray{Async}() if more than 1000 results are retrieved?

**Comment by ryancrawcour** [comment]
toArray will go fill an array with all the results that match. where the executeNext will fetch just the first page of results and stop. When you call executeNext with a continuation token it will then fetch the next set of results. 

You can use maxItemCount in requestOptions (the 3rd parameter of the createDocumentQuery method) which goes over the wire as x-ms-max-item-count HTTP header to control how many records each trip to the server returns. 

In the case of toArray, setting the maxItemCount to 1 when there are 1,000 results means that each trip to the server will fetch 1 record and there will be 1,000 trips to the server until hasMoreResults == false.

I will make a note to update the documentation for this. 

PS. we will gladly accept PR contributions to the node.js driver to update this if you would like to contribute.
