### ISSUE TITLE
hasMoreResults() gives wrong answer when (items mod maxItemCount) is 0

### ISSUE THREAD

**Issue by lmaccherone** [Azure/azure-documentdb-node#87]
Let's say I have 4000 items in my database and I use readDocuments().executeNext with a maxItemCount of 1000. After I've gotten back all four pages, hasMoreResults() still returns true. Calling executeNext() one more time causes hasMoreResults() to return false so everything works, but it adds an unneeded round trip.

**Comment by ryancrawcour** [comment]
It's not an SDK issue, but will open a bug to investigate backend behavior.
